#  Copyright 2023 Edwin.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

abbr --add t "terraform"
abbr --add ti "terraform init"
abbr --add tp "terraform plan"
abbr --add ta "terraform apply"
abbr --add tw "terraform workspace"
abbr --add twl "terraform workspace list"
abbr --add tws "terraform workspace select"
abbr --add twd "terraform workspace delete"
abbr --add twn "terraform workspace new"
abbr --add tws "terraform workspace show"
abbr --add tpdes "terraform plan -destroy"
abbr --add tades "terraform apply -destroy"
abbr --add tpref "terraform plan -refresh-only"
abbr --add tpaa "terraform plan -auto-approve"
abbr --add tplf "terraform plan -lock=false"
abbr --add talf "terraform apply -lock=false"
abbr --add tpdesref "terraform plan -destroy -refresh-only"
abbr --add tprefdes "terraform plan -refresh-only -destroy"
abbr --add tpdesaa "terraform plan -destroy -auto-approve"
abbr --add tpaades "terraform plan -auto-approve -destroy"
abbr --add tpdeslf "terraform plan -destroy -lock=false"
abbr --add tadeslf "terraform apply -destroy -lock=false"
abbr --add tplfdes "terraform plan -lock=false -destroy"
abbr --add talfdes "terraform apply -lock=false -destroy"
abbr --add tprefaa "terraform plan -refresh-only -auto-approve"
abbr --add tpaaref "terraform plan -auto-approve -refresh-only"
abbr --add tpreflf "terraform plan -refresh-only -lock=false"
abbr --add tplfref "terraform plan -lock=false -refresh-only"
abbr --add tpaalf "terraform plan -auto-approve -lock=false"
abbr --add tplfaa "terraform plan -lock=false -auto-approve"
abbr --add tpdesrefaa "terraform plan -destroy -refresh-only -auto-approve"
abbr --add tpdesaaref "terraform plan -destroy -auto-approve -refresh-only"
abbr --add tprefdesaa "terraform plan -refresh-only -destroy -auto-approve"
abbr --add tprefaades "terraform plan -refresh-only -auto-approve -destroy"
abbr --add tpaadesref "terraform plan -auto-approve -destroy -refresh-only"
abbr --add tpaarefdes "terraform plan -auto-approve -refresh-only -destroy"
abbr --add tpdesreflf "terraform plan -destroy -refresh-only -lock=false"
abbr --add tpdeslfref "terraform plan -destroy -lock=false -refresh-only"
abbr --add tprefdeslf "terraform plan -refresh-only -destroy -lock=false"
abbr --add tpreflfdes "terraform plan -refresh-only -lock=false -destroy"
abbr --add tplfdesref "terraform plan -lock=false -destroy -refresh-only"
abbr --add tplfrefdes "terraform plan -lock=false -refresh-only -destroy"
abbr --add tpdesaalf "terraform plan -destroy -auto-approve -lock=false"
abbr --add tpdeslfaa "terraform plan -destroy -lock=false -auto-approve"
abbr --add tpaadeslf "terraform plan -auto-approve -destroy -lock=false"
abbr --add tpaalfdes "terraform plan -auto-approve -lock=false -destroy"
abbr --add tplfdesaa "terraform plan -lock=false -destroy -auto-approve"
abbr --add tplfaades "terraform plan -lock=false -auto-approve -destroy"
abbr --add tprefaalf "terraform plan -refresh-only -auto-approve -lock=false"
abbr --add tpreflfaa "terraform plan -refresh-only -lock=false -auto-approve"
abbr --add tpaareflf "terraform plan -auto-approve -refresh-only -lock=false"
abbr --add tpaalfref "terraform plan -auto-approve -lock=false -refresh-only"
abbr --add tplfrefaa "terraform plan -lock=false -refresh-only -auto-approve"
abbr --add tplfaaref "terraform plan -lock=false -auto-approve -refresh-only"
abbr --add tpdesrefaalf "terraform plan -destroy -refresh-only -auto-approve -lock=false"
abbr --add tpdesreflfaa "terraform plan -destroy -refresh-only -lock=false -auto-approve"
abbr --add tpdesaareflf "terraform plan -destroy -auto-approve -refresh-only -lock=false"
abbr --add tpdesaalfref "terraform plan -destroy -auto-approve -lock=false -refresh-only"
abbr --add tpdeslfrefaa "terraform plan -destroy -lock=false -refresh-only -auto-approve"
abbr --add tpdeslfaaref "terraform plan -destroy -lock=false -auto-approve -refresh-only"
abbr --add tprefdesaalf "terraform plan -refresh-only -destroy -auto-approve -lock=false"
abbr --add tprefdeslfaa "terraform plan -refresh-only -destroy -lock=false -auto-approve"
abbr --add tprefaadeslf "terraform plan -refresh-only -auto-approve -destroy -lock=false"
abbr --add tprefaalfdes "terraform plan -refresh-only -auto-approve -lock=false -destroy"
abbr --add tpreflfdesaa "terraform plan -refresh-only -lock=false -destroy -auto-approve"
abbr --add tpreflfaades "terraform plan -refresh-only -lock=false -auto-approve -destroy"
abbr --add tpaadesreflf "terraform plan -auto-approve -destroy -refresh-only -lock=false"
abbr --add tpaadeslfref "terraform plan -auto-approve -destroy -lock=false -refresh-only"
abbr --add tpaarefdeslf "terraform plan -auto-approve -refresh-only -destroy -lock=false"
abbr --add tpaareflfdes "terraform plan -auto-approve -refresh-only -lock=false -destroy"
abbr --add tpaalfdesref "terraform plan -auto-approve -lock=false -destroy -refresh-only"
abbr --add tpaalfrefdes "terraform plan -auto-approve -lock=false -refresh-only -destroy"
abbr --add tplfdesrefaa "terraform plan -lock=false -destroy -refresh-only -auto-approve"
abbr --add tplfdesaaref "terraform plan -lock=false -destroy -auto-approve -refresh-only"
abbr --add tplfrefdesaa "terraform plan -lock=false -refresh-only -destroy -auto-approve"
abbr --add tplfrefaades "terraform plan -lock=false -refresh-only -auto-approve -destroy"
abbr --add tplfaadesref "terraform plan -lock=false -auto-approve -destroy -refresh-only"
abbr --add tplfaarefdes "terraform plan -lock=false -auto-approve -refresh-only -destroy"
abbr --add tpno-c "terraform plan -no-color"
abbr --add tano-c "terraform apply -no-color"
abbr --add tpdesno-c "terraform plan -destroy -no-color"
abbr --add tadesno-c "terraform apply -destroy -no-color"
abbr --add tprefno-c "terraform plan -refresh-only -no-color"
abbr --add tpaano-c "terraform plan -auto-approve -no-color"
abbr --add tplfno-c "terraform plan -lock=false -no-color"
abbr --add talfno-c "terraform apply -lock=false -no-color"
abbr --add tpdesrefno-c "terraform plan -destroy -refresh-only -no-color"
abbr --add tprefdesno-c "terraform plan -refresh-only -destroy -no-color"
abbr --add tpdesaano-c "terraform plan -destroy -auto-approve -no-color"
abbr --add tpaadesno-c "terraform plan -auto-approve -destroy -no-color"
abbr --add tpdeslfno-c "terraform plan -destroy -lock=false -no-color"
abbr --add tadeslfno-c "terraform apply -destroy -lock=false -no-color"
abbr --add tplfdesno-c "terraform plan -lock=false -destroy -no-color"
abbr --add talfdesno-c "terraform apply -lock=false -destroy -no-color"
abbr --add tprefaano-c "terraform plan -refresh-only -auto-approve -no-color"
abbr --add tpaarefno-c "terraform plan -auto-approve -refresh-only -no-color"
abbr --add tpreflfno-c "terraform plan -refresh-only -lock=false -no-color"
abbr --add tplfrefno-c "terraform plan -lock=false -refresh-only -no-color"
abbr --add tpaalfno-c "terraform plan -auto-approve -lock=false -no-color"
abbr --add tplfaano-c "terraform plan -lock=false -auto-approve -no-color"
abbr --add tpdesrefaano-c "terraform plan -destroy -refresh-only -auto-approve -no-color"
abbr --add tpdesaarefno-c "terraform plan -destroy -auto-approve -refresh-only -no-color"
abbr --add tprefdesaano-c "terraform plan -refresh-only -destroy -auto-approve -no-color"
abbr --add tprefaadesno-c "terraform plan -refresh-only -auto-approve -destroy -no-color"
abbr --add tpaadesrefno-c "terraform plan -auto-approve -destroy -refresh-only -no-color"
abbr --add tpaarefdesno-c "terraform plan -auto-approve -refresh-only -destroy -no-color"
abbr --add tpdesreflfno-c "terraform plan -destroy -refresh-only -lock=false -no-color"
abbr --add tpdeslfrefno-c "terraform plan -destroy -lock=false -refresh-only -no-color"
abbr --add tprefdeslfno-c "terraform plan -refresh-only -destroy -lock=false -no-color"
abbr --add tpreflfdesno-c "terraform plan -refresh-only -lock=false -destroy -no-color"
abbr --add tplfdesrefno-c "terraform plan -lock=false -destroy -refresh-only -no-color"
abbr --add tplfrefdesno-c "terraform plan -lock=false -refresh-only -destroy -no-color"
abbr --add tpdesaalfno-c "terraform plan -destroy -auto-approve -lock=false -no-color"
abbr --add tpdeslfaano-c "terraform plan -destroy -lock=false -auto-approve -no-color"
abbr --add tpaadeslfno-c "terraform plan -auto-approve -destroy -lock=false -no-color"
abbr --add tpaalfdesno-c "terraform plan -auto-approve -lock=false -destroy -no-color"
abbr --add tplfdesaano-c "terraform plan -lock=false -destroy -auto-approve -no-color"
abbr --add tplfaadesno-c "terraform plan -lock=false -auto-approve -destroy -no-color"
abbr --add tprefaalfno-c "terraform plan -refresh-only -auto-approve -lock=false -no-color"
abbr --add tpreflfaano-c "terraform plan -refresh-only -lock=false -auto-approve -no-color"
abbr --add tpaareflfno-c "terraform plan -auto-approve -refresh-only -lock=false -no-color"
abbr --add tpaalfrefno-c "terraform plan -auto-approve -lock=false -refresh-only -no-color"
abbr --add tplfrefaano-c "terraform plan -lock=false -refresh-only -auto-approve -no-color"
abbr --add tplfaarefno-c "terraform plan -lock=false -auto-approve -refresh-only -no-color"
abbr --add tpdesrefaalfno-c "terraform plan -destroy -refresh-only -auto-approve -lock=false -no-color"
abbr --add tpdesreflfaano-c "terraform plan -destroy -refresh-only -lock=false -auto-approve -no-color"
abbr --add tpdesaareflfno-c "terraform plan -destroy -auto-approve -refresh-only -lock=false -no-color"
abbr --add tpdesaalfrefno-c "terraform plan -destroy -auto-approve -lock=false -refresh-only -no-color"
abbr --add tpdeslfrefaano-c "terraform plan -destroy -lock=false -refresh-only -auto-approve -no-color"
abbr --add tpdeslfaarefno-c "terraform plan -destroy -lock=false -auto-approve -refresh-only -no-color"
abbr --add tprefdesaalfno-c "terraform plan -refresh-only -destroy -auto-approve -lock=false -no-color"
abbr --add tprefdeslfaano-c "terraform plan -refresh-only -destroy -lock=false -auto-approve -no-color"
abbr --add tprefaadeslfno-c "terraform plan -refresh-only -auto-approve -destroy -lock=false -no-color"
abbr --add tprefaalfdesno-c "terraform plan -refresh-only -auto-approve -lock=false -destroy -no-color"
abbr --add tpreflfdesaano-c "terraform plan -refresh-only -lock=false -destroy -auto-approve -no-color"
abbr --add tpreflfaadesno-c "terraform plan -refresh-only -lock=false -auto-approve -destroy -no-color"
abbr --add tpaadesreflfno-c "terraform plan -auto-approve -destroy -refresh-only -lock=false -no-color"
abbr --add tpaadeslfrefno-c "terraform plan -auto-approve -destroy -lock=false -refresh-only -no-color"
abbr --add tpaarefdeslfno-c "terraform plan -auto-approve -refresh-only -destroy -lock=false -no-color"
abbr --add tpaareflfdesno-c "terraform plan -auto-approve -refresh-only -lock=false -destroy -no-color"
abbr --add tpaalfdesrefno-c "terraform plan -auto-approve -lock=false -destroy -refresh-only -no-color"
abbr --add tpaalfrefdesno-c "terraform plan -auto-approve -lock=false -refresh-only -destroy -no-color"
abbr --add tplfdesrefaano-c "terraform plan -lock=false -destroy -refresh-only -auto-approve -no-color"
abbr --add tplfdesaarefno-c "terraform plan -lock=false -destroy -auto-approve -refresh-only -no-color"
abbr --add tplfrefdesaano-c "terraform plan -lock=false -refresh-only -destroy -auto-approve -no-color"
abbr --add tplfrefaadesno-c "terraform plan -lock=false -refresh-only -auto-approve -destroy -no-color"
abbr --add tplfaadesrefno-c "terraform plan -lock=false -auto-approve -destroy -refresh-only -no-color"
abbr --add tplfaarefdesno-c "terraform plan -lock=false -auto-approve -refresh-only -destroy -no-color"
